fragment PageParts on Page {
  __typename
  navbar {
    __typename
    brand
    links {
      __typename
      label
      href
    }
    ctaText
    ctaHref
  }
  hero {
    __typename
    badge
    headlinePart1
    headlineHighlight
    headlinePart2
    subheadline
    description
    stats {
      __typename
      value
      label
    }
    ctaPrimaryText
    ctaSecondaryText
    ctaFootnote
  }
  aboutBlake {
    __typename
    title
    description
    videoFile
    stats {
      __typename
      value
      label
    }
  }
  suburbs {
    __typename
    title
    description
    steps {
      __typename
      title
      description
    }
    checkerTitle
    checkerPlaceholder
    checkerButtonText
    checkerFootnote
    warningTitle
    warningText
  }
  socialProof {
    __typename
    title
    subtitle
    testimonials {
      __typename
      stat
      quote
      name
      agency
      image
      headshot
    }
    beforeTitle
    beforeItems {
      __typename
      text
    }
    afterTitle
    afterItems {
      __typename
      text
    }
  }
  investment {
    __typename
    title
    subtitle
    valueStack {
      __typename
      role
      detail
      price
    }
    totalValue
    priceLabel
    price
    pricePeriod
    priceNote
    includes {
      __typename
      text
    }
    roiTitle
    monthlyInvestment
    avgCommission
    breakEven
    avgListings
    avgListingsDetail
  }
  process {
    __typename
    title
    subtitle
    steps {
      __typename
      week
      title
      bullets {
        __typename
        text
      }
    }
  }
  qualification {
    __typename
    title
    subtitle
    dontApply {
      __typename
      title
      description
    }
    perfectIf {
      __typename
      title
      description
    }
  }
  cta {
    __typename
    headline
    subheadline
    description
    formTitle
    submitText
    footnote
    trustBadges {
      __typename
      text
    }
  }
  faq {
    __typename
    title
    items {
      __typename
      question
      answer
    }
  }
  portfolio {
    __typename
    title
    subtitle
    items {
      __typename
      title
      type
      description
      stat
      videoFile
      reelUrl
      image
    }
  }
  showcase {
    __typename
    title
    subtitle
    agentName
    agentSuburb
    stats {
      __typename
      label
      before
      after
    }
    quote
  }
  checkAvailability {
    __typename
    headline
    subtitle
    scarcityWarning
    stats {
      __typename
      value
      label
    }
    bookingTitle
    bookingSubtitle
    auditTitle
    auditIntro
    auditItems {
      __typename
      title
      description
    }
    auditFootnote
    footnote
  }
  stickyCta {
    __typename
    text
    buttonText
    buttonHref
  }
  footer {
    __typename
    brand
    tagline
    quickLinks {
      __typename
      label
      href
    }
    resources {
      __typename
      label
      href
    }
    email
    phone
    location
    copyright
  }
}
